### ISSUE TITLE
Parallelize MEDLINE parser

### ISSUE THREAD

**Issue by titipata** [titipata/pubmed_parser#19]
I think we can speed up the parser a lot by parallelize this [L105](https://github.com/titipata/pubmed_parser/blob/master/pubmed_parser/medline_parser.py#L105)

**Comment by titipata** [comment]
I tried the following code, 

```python
from multiprocessing import Pool
pool = Pool()
dict_out = pool.map(parse_article_info, medline_citations)
```

However, I had error as follows. 

```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/titipat/anaconda3/lib/python3.5/site-packages/lxml/_elementpath.py", line 291, in find
    _next = it.next
AttributeError: 'generator' object has no attribute 'next'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/titipat/anaconda3/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/titipat/anaconda3/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/titipat/Desktop/Git/pubmed_parser/pubmed_parser/medline_parser.py", line 36, in parse_article_info
    article = medline.find('Article')
  File "src/lxml/lxml.etree.pyx", line 1537, in lxml.etree._Element.find (src/lxml/lxml.etree.c:57105)
  File "/Users/titipat/anaconda3/lib/python3.5/site-packages/lxml/_elementpath.py", line 293, in find
    return next(it)
  File "/Users/titipat/anaconda3/lib/python3.5/site-packages/lxml/_elementpath.py", line 89, in select
    for e in elem.iterchildren(tag):
  File "src/lxml/lxml.etree.pyx", line 1443, in lxml.etree._Element.iterchildren (src/lxml/lxml.etree.c:56147)
  File "src/lxml/lxml.etree.pyx", line 2816, in lxml.etree.ElementChildIterator.__cinit__ (src/lxml/lxml.etree.c:73441)
  File "src/lxml/apihelpers.pxi", line 19, in lxml.etree._assertValidNode (src/lxml/lxml.etree.c:15163)
AssertionError: invalid Element proxy at 9548713416
"""

The above exception was the direct cause of the following exception:

AssertionError                            Traceback (most recent call last)
<ipython-input-84-c4ed8d34e616> in <module>()
      1 from multiprocessing import Pool
      2 pool = Pool()
----> 3 dict_out = pool.map(pp.medline_parser.parse_article_info, list(medline))

/Users/titipat/anaconda3/lib/python3.5/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    258         in a list that is returned.
    259         '''
--> 260         return self._map_async(func, iterable, mapstar, chunksize).get()
    261 
    262     def starmap(self, func, iterable, chunksize=None):

/Users/titipat/anaconda3/lib/python3.5/multiprocessing/pool.py in get(self, timeout)
    606             return self._value
    607         else:
--> 608             raise self._value
    609 
    610     def _set(self, i, obj):

AssertionError: invalid Element proxy at 9548713416
```

Not quite sure how to solve this issue.

**Comment by daniel-acuna** [comment]
Does it work on Python 2.7?

**Comment by titipata** [comment]
We discussed and agreed that we don't need to parallel parsing right now. I'll close the issue.
