### ISSUE TITLE
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by deakkon** [titipata/pubmed_parser#53]
Started hapenning a few days ago. Tried reinstalling a few libs, but to no avail. Do you have a suggestion? 

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from util import *
  File "/home/sevajuri/projects/zsl/util.py", line 8, in <module>
    import pubmed_parser as pp
  File "/home/sevajuri/anaconda2/envs/tf/lib/python2.7/site-packages/pubmed_parser/__init__.py", line 7, in <module>
    from .pubmed_oa_parser import list_xml_path, \
  File "/home/sevajuri/anaconda2/envs/tf/lib/python2.7/site-packages/pubmed_parser/pubmed_oa_parser.py", line 2, in <module>
    from lxml import etree
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory

**Comment by bluenex** [comment]
Refer to [this issue from another project](https://github.com/poldracklab/mriqc/issues/371), the problem seems to be because conda environment. Could you try this `conda install icu=56.1` and see if it fixes?

**Comment by marescpla** [comment]
I just started anaconda and opened a new enviroment, and I can't use spyder because I get the error:

Traceback (most recent call last):
File "/home/aeroarms/anaconda3/envs/PN/bin/spyder", line 11, in 
sys.exit(main())
File "/home/aeroarms/anaconda3/envs/PN/lib/python2.7/site-packages/spyder/app/start.py", line 159, in main
from spyder.app import mainwindow
File "/home/aeroarms/anaconda3/envs/PN/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 92, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "/home/aeroarms/anaconda3/envs/PN/lib/python2.7/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in 
from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory

-----------------------------------------------------------------------------------

Then I tried: 
$ conda install icu=56.1

And I get:
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - icu=56.1

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



------------------------------------------------------------------------------------------
Any sugestions what should I do to use Spyder? = /

**Comment by titipata** [comment]
I will close this issue due to inactivity. It's also not relevance directly to the repository.
